/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class ArtaLele_ extends javax.swing.JFrame {

    /**
     * Creates new form ArtaLele_
     */
    public ArtaLele_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dftrpMenuItem = new javax.swing.JMenuItem();
        dftrkManuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        masukMenuItem = new javax.swing.JMenuItem();
        keluarMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        laporanmMenuItem = new javax.swing.JMenuItem();
        laporankMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/server.png"))); // NOI18N
        jMenu1.setText("Pengaturan");

        dftrpMenuItem.setText("Base harga");
        dftrpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dftrpMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(dftrpMenuItem);

        dftrkManuItem.setText("Data Karyawan");
        dftrkManuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dftrkManuItemActionPerformed(evt);
            }
        });
        jMenu1.add(dftrkManuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaction.png"))); // NOI18N
        jMenu2.setText("Transaksi");

        masukMenuItem.setText("Masuk");
        masukMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(masukMenuItem);

        keluarMenuItem.setText("Keluar");
        keluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(keluarMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ux.png"))); // NOI18N
        jMenu3.setText("Laporan");

        laporanmMenuItem.setText("Masuk");
        laporanmMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanmMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(laporanmMenuItem);

        laporankMenuItem.setText("Keluar");
        jMenu3.add(laporankMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        jMenu4.setText("Keluar");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dftrpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dftrpMenuItemActionPerformed
        // go to DataPembelian
        DataPembelian df = new DataPembelian();
        df.setVisible(true);
        df.pack();
        df.setLocationRelativeTo(null);
        df.setDefaultCloseOperation(ArtaLele_.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_dftrpMenuItemActionPerformed

    private void dftrkManuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dftrkManuItemActionPerformed
        // go to DataKaryawan
        DataKaryawan dk = new DataKaryawan();
        dk.setVisible(true);
        dk.pack();
        dk.setLocationRelativeTo(null);
        dk.setDefaultCloseOperation(ArtaLele_.EXIT_ON_CLOSE);
    }//GEN-LAST:event_dftrkManuItemActionPerformed

    private void masukMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukMenuItemActionPerformed
        // go to TransaksiMasuk
        TransaksiMasuk tm = new TransaksiMasuk();
        tm.setVisible(true);
        tm.pack();
        tm.setLocationRelativeTo(null);
        tm.setDefaultCloseOperation(ArtaLele_.EXIT_ON_CLOSE);
    }//GEN-LAST:event_masukMenuItemActionPerformed

    private void keluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarMenuItemActionPerformed
        // go to TransaksiKeluar
        TransaksiKeluar tk = new TransaksiKeluar();
        tk.setVisible(true);
        tk.pack();
        tk.setLocationRelativeTo(null);
        tk.setDefaultCloseOperation(ArtaLele_.EXIT_ON_CLOSE);
    }//GEN-LAST:event_keluarMenuItemActionPerformed

    private void laporanmMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanmMenuItemActionPerformed
        // Tgo to Laporan
    }//GEN-LAST:event_laporanmMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArtaLele_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArtaLele_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArtaLele_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArtaLele_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ArtaLele_().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dftrkManuItem;
    private javax.swing.JMenuItem dftrpMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem keluarMenuItem;
    private javax.swing.JMenuItem laporankMenuItem;
    private javax.swing.JMenuItem laporanmMenuItem;
    private javax.swing.JMenuItem masukMenuItem;
    // End of variables declaration//GEN-END:variables
}
